### ISSUE TITLE
4 references to labels for gateway_service_N are not defined anywhere

### ISSUE THREAD

**Issue by nienienienie** [ernestaskardzys/scalable-spring-container#1]
in nginx definition there seems to be 4 references to labels for gateway_service_N
```
    upstream app_servers {
        # Use server with least connections
        least_conn;

        server gateway-service_1:8080;
        server gateway-service_2:8080;
        server gateway-service_3:8080;
        server gateway-service_4:8080;
    }
```

but those are not defined anywhere

did you mean rather sth like in docker-compose
```
  gateway-service:
    build: gateway-service
    ...
    deploy:
      replicas: 4 // <- !!!
```
